# Project information
site_name: 5FA-72-EVG
site_url: https://5-72.com/
site_author: Ismail Dalgatov
site_description: >-
  5-72 is an open-source documentation from sound-engineers and musicians.
# Repository
repo_name: ismaildalgatov/5-72
repo_url: https://github.com/ismaildalgatov/5-72

# Copyright
copyright: Copyright &copy; 2020 - 2022 Ismail Dalgatov

# Configuration
theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
#  - redirects:
#      redirect_maps:
#        changelog/insiders.md: insiders/changelog.md
#        conventions.md: philosophy.md
#        reference/abbreviations.md: reference/tooltips.md
#        reference/meta-tags.md: reference/index.md
#        reference/variables.md: https://mkdocs-macros-plugin.readthedocs.io/
#        sponsorship.md: insiders/index.md
#        upgrading.md: upgrade.md
#  - minify:
#      minify_html: true

# Customization
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Pqdc2ekkWw
    - icon: fontawesome/brands/github
      link: https://github.com/ismaildalgatov
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/teamseshisma
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/teamseshisma
    - icon: fontawesome/brands/telegram
      link: https://t.me/ismaildalgatov

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - pymdownx.snippets
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
#  - pymdownx.emoji:
#      emoji_generator: !!python/name:materialx.emoji.to_svg
#      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: ismaildalgatov
      repo: 5-72
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Database:
    - index.md
    - Chains:
        - Zola Jesus - Exhumed: zola-jesus-exhumed.md
        - Arigto - Threat that lies in despair: arigto-threat-that-lies-in-despair.md
        - Kendrick Lamar, SZA - All The Stars: kendrick-lamar-sza-all-the-stars.md
        - Twenty One Pilots - Chlorine: twenty-one-pilots-chlorine.md
        - The Monuments, Mick Gordon - Lavos: monuments-mick-gordon-lavos.md
        - The Weeknd - Alone Again: the-weeknd-alone-again.md
        - Other:
            - Drum Machines: drum-machines/list.md
  - Changelog: changelog.md
