name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build docs
        run: |
          pip install -r requirements.txt
          pip install wheel
          pip install mkdocs-redirects
          pip install mkdocs-minify-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          mkdocs build
          mkdocs gh-deploy --force
